// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: protos/authentication_state.proto

package models

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// What the server will persist when requesting the client to authenticate.
// The state is identified by an UUIDv7, and the timestamp part of it allows it
// to be ordered and expired by only observing the key.
// Ref: "auth-state:$id"
type AuthenticationState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserVerification   string                 `protobuf:"bytes,1,opt,name=user_verification,json=userVerification,proto3" json:"user_verification,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Challenge          string                 `protobuf:"bytes,3,opt,name=challenge,proto3" json:"challenge,omitempty"`
	AllowedCredentials [][]byte               `protobuf:"bytes,4,rep,name=allowed_credentials,json=allowedCredentials,proto3" json:"allowed_credentials,omitempty"`
	ExpiresAt          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Types that are assignable to Type:
	//
	//	*AuthenticationState_Enroll
	//	*AuthenticationState_SignIn
	//	*AuthenticationState_ConfirmSshKey
	//	*AuthenticationState_ConfirmSignin
	Type isAuthenticationState_Type `protobuf_oneof:"type"`
}

func (x *AuthenticationState) Reset() {
	*x = AuthenticationState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_authentication_state_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenticationState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationState) ProtoMessage() {}

func (x *AuthenticationState) ProtoReflect() protoreflect.Message {
	mi := &file_protos_authentication_state_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationState.ProtoReflect.Descriptor instead.
func (*AuthenticationState) Descriptor() ([]byte, []int) {
	return file_protos_authentication_state_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticationState) GetUserVerification() string {
	if x != nil {
		return x.UserVerification
	}
	return ""
}

func (x *AuthenticationState) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthenticationState) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

func (x *AuthenticationState) GetAllowedCredentials() [][]byte {
	if x != nil {
		return x.AllowedCredentials
	}
	return nil
}

func (x *AuthenticationState) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (m *AuthenticationState) GetType() isAuthenticationState_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *AuthenticationState) GetEnroll() *AuthenticationStateEnroll {
	if x, ok := x.GetType().(*AuthenticationState_Enroll); ok {
		return x.Enroll
	}
	return nil
}

func (x *AuthenticationState) GetSignIn() *AthenticationStateSignIn {
	if x, ok := x.GetType().(*AuthenticationState_SignIn); ok {
		return x.SignIn
	}
	return nil
}

func (x *AuthenticationState) GetConfirmSshKey() *AthenticationStateConfirmSshKey {
	if x, ok := x.GetType().(*AuthenticationState_ConfirmSshKey); ok {
		return x.ConfirmSshKey
	}
	return nil
}

func (x *AuthenticationState) GetConfirmSignin() *AuthenticationStateConfirmSignin {
	if x, ok := x.GetType().(*AuthenticationState_ConfirmSignin); ok {
		return x.ConfirmSignin
	}
	return nil
}

type isAuthenticationState_Type interface {
	isAuthenticationState_Type()
}

type AuthenticationState_Enroll struct {
	Enroll *AuthenticationStateEnroll `protobuf:"bytes,10,opt,name=enroll,proto3,oneof"`
}

type AuthenticationState_SignIn struct {
	SignIn *AthenticationStateSignIn `protobuf:"bytes,11,opt,name=sign_in,json=signIn,proto3,oneof"`
}

type AuthenticationState_ConfirmSshKey struct {
	ConfirmSshKey *AthenticationStateConfirmSshKey `protobuf:"bytes,12,opt,name=confirm_ssh_key,json=confirmSshKey,proto3,oneof"`
}

type AuthenticationState_ConfirmSignin struct {
	ConfirmSignin *AuthenticationStateConfirmSignin `protobuf:"bytes,14,opt,name=confirm_signin,json=confirmSignin,proto3,oneof"`
}

func (*AuthenticationState_Enroll) isAuthenticationState_Type() {}

func (*AuthenticationState_SignIn) isAuthenticationState_Type() {}

func (*AuthenticationState_ConfirmSshKey) isAuthenticationState_Type() {}

func (*AuthenticationState_ConfirmSignin) isAuthenticationState_Type() {}

// User is enrolling a new credential.
type AuthenticationStateEnroll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *AuthenticationStateEnroll) Reset() {
	*x = AuthenticationStateEnroll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_authentication_state_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenticationStateEnroll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationStateEnroll) ProtoMessage() {}

func (x *AuthenticationStateEnroll) ProtoReflect() protoreflect.Message {
	mi := &file_protos_authentication_state_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationStateEnroll.ProtoReflect.Descriptor instead.
func (*AuthenticationStateEnroll) Descriptor() ([]byte, []int) {
	return file_protos_authentication_state_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticationStateEnroll) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// User is confirming an enroll request
type AuthenticationStateConfirmSignin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SigninRequestId string `protobuf:"bytes,1,opt,name=signin_request_id,json=signinRequestId,proto3" json:"signin_request_id,omitempty"`
	SessionId       string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *AuthenticationStateConfirmSignin) Reset() {
	*x = AuthenticationStateConfirmSignin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_authentication_state_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenticationStateConfirmSignin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationStateConfirmSignin) ProtoMessage() {}

func (x *AuthenticationStateConfirmSignin) ProtoReflect() protoreflect.Message {
	mi := &file_protos_authentication_state_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationStateConfirmSignin.ProtoReflect.Descriptor instead.
func (*AuthenticationStateConfirmSignin) Descriptor() ([]byte, []int) {
	return file_protos_authentication_state_proto_rawDescGZIP(), []int{2}
}

func (x *AuthenticationStateConfirmSignin) GetSigninRequestId() string {
	if x != nil {
		return x.SigninRequestId
	}
	return ""
}

func (x *AuthenticationStateConfirmSignin) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// The user has asked to sign in.
type AthenticationStateSignIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AthenticationStateSignIn) Reset() {
	*x = AthenticationStateSignIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_authentication_state_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AthenticationStateSignIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AthenticationStateSignIn) ProtoMessage() {}

func (x *AthenticationStateSignIn) ProtoReflect() protoreflect.Message {
	mi := &file_protos_authentication_state_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AthenticationStateSignIn.ProtoReflect.Descriptor instead.
func (*AthenticationStateSignIn) Descriptor() ([]byte, []int) {
	return file_protos_authentication_state_proto_rawDescGZIP(), []int{3}
}

// The user has asked to confirm a SSH key.
type AthenticationStateConfirmSshKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyId string `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
}

func (x *AthenticationStateConfirmSshKey) Reset() {
	*x = AthenticationStateConfirmSshKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_authentication_state_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AthenticationStateConfirmSshKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AthenticationStateConfirmSshKey) ProtoMessage() {}

func (x *AthenticationStateConfirmSshKey) ProtoReflect() protoreflect.Message {
	mi := &file_protos_authentication_state_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AthenticationStateConfirmSshKey.ProtoReflect.Descriptor instead.
func (*AthenticationStateConfirmSshKey) Descriptor() ([]byte, []int) {
	return file_protos_authentication_state_proto_rawDescGZIP(), []int{4}
}

func (x *AthenticationStateConfirmSshKey) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

var File_protos_authentication_state_proto protoreflect.FileDescriptor

var file_protos_authentication_state_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8d, 0x04, 0x0a,
	0x13, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x76, 0x65, 0x72,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x10, 0x75, 0x73, 0x65, 0x72, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68,
	0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63,
	0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x12, 0x2f, 0x0a, 0x13, 0x61, 0x6c, 0x6c, 0x6f,
	0x77, 0x65, 0x64, 0x5f, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x12, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x43, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x39, 0x0a, 0x0a, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x73, 0x41, 0x74, 0x12, 0x3b, 0x0a, 0x06, 0x65, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x41, 0x75,
	0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x48, 0x00, 0x52, 0x06, 0x65, 0x6e, 0x72, 0x6f, 0x6c,
	0x6c, 0x12, 0x3b, 0x0a, 0x07, 0x73, 0x69, 0x67, 0x6e, 0x5f, 0x69, 0x6e, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x41, 0x74, 0x68, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x69,
	0x67, 0x6e, 0x49, 0x6e, 0x48, 0x00, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x12, 0x51,
	0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x5f, 0x73, 0x73, 0x68, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x41, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x53, 0x73, 0x68, 0x4b, 0x65, 0x79,
	0x48, 0x00, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x53, 0x73, 0x68, 0x4b, 0x65,
	0x79, 0x12, 0x51, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x5f, 0x73, 0x69, 0x67,
	0x6e, 0x69, 0x6e, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x53, 0x69, 0x67,
	0x6e, 0x69, 0x6e, 0x48, 0x00, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x53, 0x69,
	0x67, 0x6e, 0x69, 0x6e, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x3a, 0x0a, 0x19,
	0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x6d, 0x0a, 0x20, 0x41, 0x75, 0x74, 0x68,
	0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x12, 0x2a, 0x0a, 0x11,
	0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x1a, 0x0a, 0x18, 0x41, 0x74, 0x68, 0x65, 0x6e,
	0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67,
	0x6e, 0x49, 0x6e, 0x22, 0x38, 0x0a, 0x1f, 0x41, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d,
	0x53, 0x73, 0x68, 0x4b, 0x65, 0x79, 0x12, 0x15, 0x0a, 0x06, 0x6b, 0x65, 0x79, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6b, 0x65, 0x79, 0x49, 0x64, 0x42, 0x11, 0x5a,
	0x0f, 0x2e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_authentication_state_proto_rawDescOnce sync.Once
	file_protos_authentication_state_proto_rawDescData = file_protos_authentication_state_proto_rawDesc
)

func file_protos_authentication_state_proto_rawDescGZIP() []byte {
	file_protos_authentication_state_proto_rawDescOnce.Do(func() {
		file_protos_authentication_state_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_authentication_state_proto_rawDescData)
	})
	return file_protos_authentication_state_proto_rawDescData
}

var file_protos_authentication_state_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protos_authentication_state_proto_goTypes = []interface{}{
	(*AuthenticationState)(nil),              // 0: models.AuthenticationState
	(*AuthenticationStateEnroll)(nil),        // 1: models.AuthenticationStateEnroll
	(*AuthenticationStateConfirmSignin)(nil), // 2: models.AuthenticationStateConfirmSignin
	(*AthenticationStateSignIn)(nil),         // 3: models.AthenticationStateSignIn
	(*AthenticationStateConfirmSshKey)(nil),  // 4: models.AthenticationStateConfirmSshKey
	(*timestamppb.Timestamp)(nil),            // 5: google.protobuf.Timestamp
}
var file_protos_authentication_state_proto_depIdxs = []int32{
	5, // 0: models.AuthenticationState.expires_at:type_name -> google.protobuf.Timestamp
	1, // 1: models.AuthenticationState.enroll:type_name -> models.AuthenticationStateEnroll
	3, // 2: models.AuthenticationState.sign_in:type_name -> models.AthenticationStateSignIn
	4, // 3: models.AuthenticationState.confirm_ssh_key:type_name -> models.AthenticationStateConfirmSshKey
	2, // 4: models.AuthenticationState.confirm_signin:type_name -> models.AuthenticationStateConfirmSignin
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_protos_authentication_state_proto_init() }
func file_protos_authentication_state_proto_init() {
	if File_protos_authentication_state_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_authentication_state_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthenticationState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_authentication_state_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthenticationStateEnroll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_authentication_state_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthenticationStateConfirmSignin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_authentication_state_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AthenticationStateSignIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_authentication_state_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AthenticationStateConfirmSshKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protos_authentication_state_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*AuthenticationState_Enroll)(nil),
		(*AuthenticationState_SignIn)(nil),
		(*AuthenticationState_ConfirmSshKey)(nil),
		(*AuthenticationState_ConfirmSignin)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_authentication_state_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_authentication_state_proto_goTypes,
		DependencyIndexes: file_protos_authentication_state_proto_depIdxs,
		MessageInfos:      file_protos_authentication_state_proto_msgTypes,
	}.Build()
	File_protos_authentication_state_proto = out.File
	file_protos_authentication_state_proto_rawDesc = nil
	file_protos_authentication_state_proto_goTypes = nil
	file_protos_authentication_state_proto_depIdxs = nil
}
