// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: protos/backend.proto

package models

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessLevel int32

const (
	// Required first variant in a proto enum. Will default to NORMAL.
	AccessLevel_ACCESS_LEVEL_UNSPECIFIED AccessLevel = 0
	// Requires to be logged in, and backend included in user's access.
	AccessLevel_NORMAL AccessLevel = 1
	// No authentication required - public endpoint.
	AccessLevel_PUBLIC AccessLevel = 2
)

// Enum value maps for AccessLevel.
var (
	AccessLevel_name = map[int32]string{
		0: "ACCESS_LEVEL_UNSPECIFIED",
		1: "NORMAL",
		2: "PUBLIC",
	}
	AccessLevel_value = map[string]int32{
		"ACCESS_LEVEL_UNSPECIFIED": 0,
		"NORMAL":                   1,
		"PUBLIC":                   2,
	}
)

func (x AccessLevel) Enum() *AccessLevel {
	p := new(AccessLevel)
	*p = x
	return p
}

func (x AccessLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_backend_proto_enumTypes[0].Descriptor()
}

func (AccessLevel) Type() protoreflect.EnumType {
	return &file_protos_backend_proto_enumTypes[0]
}

func (x AccessLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessLevel.Descriptor instead.
func (AccessLevel) EnumDescriptor() ([]byte, []int) {
	return file_protos_backend_proto_rawDescGZIP(), []int{0}
}

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_protos_backend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_protos_backend_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Header) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ScriptHandler struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsScript      string                 `protobuf:"bytes,1,opt,name=js_script,json=jsScript,proto3" json:"js_script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptHandler) Reset() {
	*x = ScriptHandler{}
	mi := &file_protos_backend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptHandler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptHandler) ProtoMessage() {}

func (x *ScriptHandler) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptHandler.ProtoReflect.Descriptor instead.
func (*ScriptHandler) Descriptor() ([]byte, []int) {
	return file_protos_backend_proto_rawDescGZIP(), []int{1}
}

func (x *ScriptHandler) GetJsScript() string {
	if x != nil {
		return x.JsScript
	}
	return ""
}

// Ref: "be:$fqdn" -> Backend
type Backend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fqdn          string                 `protobuf:"bytes,1,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	UpstreamUrl   string                 `protobuf:"bytes,2,opt,name=upstream_url,json=upstreamUrl,proto3" json:"upstream_url,omitempty"`
	Headers       []*Header              `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	AccessLevel   AccessLevel            `protobuf:"varint,6,opt,name=access_level,json=accessLevel,proto3,enum=models.AccessLevel" json:"access_level,omitempty"`
	ScriptHandler *ScriptHandler         `protobuf:"bytes,7,opt,name=script_handler,json=scriptHandler,proto3" json:"script_handler,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Backend) Reset() {
	*x = Backend{}
	mi := &file_protos_backend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backend) ProtoMessage() {}

func (x *Backend) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backend.ProtoReflect.Descriptor instead.
func (*Backend) Descriptor() ([]byte, []int) {
	return file_protos_backend_proto_rawDescGZIP(), []int{2}
}

func (x *Backend) GetFqdn() string {
	if x != nil {
		return x.Fqdn
	}
	return ""
}

func (x *Backend) GetUpstreamUrl() string {
	if x != nil {
		return x.UpstreamUrl
	}
	return ""
}

func (x *Backend) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Backend) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Backend) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Backend) GetAccessLevel() AccessLevel {
	if x != nil {
		return x.AccessLevel
	}
	return AccessLevel_ACCESS_LEVEL_UNSPECIFIED
}

func (x *Backend) GetScriptHandler() *ScriptHandler {
	if x != nil {
		return x.ScriptHandler
	}
	return nil
}

var File_protos_backend_proto protoreflect.FileDescriptor

const file_protos_backend_proto_rawDesc = "" +
	"\n" +
	"\x14protos/backend.proto\x12\x06models\x1a\x1fgoogle/protobuf/timestamp.proto\"2\n" +
	"\x06Header\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\",\n" +
	"\rScriptHandler\x12\x1b\n" +
	"\tjs_script\x18\x01 \x01(\tR\bjsScript\"\xd6\x02\n" +
	"\aBackend\x12\x12\n" +
	"\x04fqdn\x18\x01 \x01(\tR\x04fqdn\x12!\n" +
	"\fupstream_url\x18\x02 \x01(\tR\vupstreamUrl\x12(\n" +
	"\aheaders\x18\x03 \x03(\v2\x0e.models.HeaderR\aheaders\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x126\n" +
	"\faccess_level\x18\x06 \x01(\x0e2\x13.models.AccessLevelR\vaccessLevel\x12<\n" +
	"\x0escript_handler\x18\a \x01(\v2\x15.models.ScriptHandlerR\rscriptHandler*C\n" +
	"\vAccessLevel\x12\x1c\n" +
	"\x18ACCESS_LEVEL_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x01\x12\n" +
	"\n" +
	"\x06PUBLIC\x10\x02B\x11Z\x0f./server/modelsb\x06proto3"

var (
	file_protos_backend_proto_rawDescOnce sync.Once
	file_protos_backend_proto_rawDescData []byte
)

func file_protos_backend_proto_rawDescGZIP() []byte {
	file_protos_backend_proto_rawDescOnce.Do(func() {
		file_protos_backend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_backend_proto_rawDesc), len(file_protos_backend_proto_rawDesc)))
	})
	return file_protos_backend_proto_rawDescData
}

var file_protos_backend_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_backend_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_backend_proto_goTypes = []any{
	(AccessLevel)(0),              // 0: models.AccessLevel
	(*Header)(nil),                // 1: models.Header
	(*ScriptHandler)(nil),         // 2: models.ScriptHandler
	(*Backend)(nil),               // 3: models.Backend
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_protos_backend_proto_depIdxs = []int32{
	1, // 0: models.Backend.headers:type_name -> models.Header
	4, // 1: models.Backend.created_at:type_name -> google.protobuf.Timestamp
	4, // 2: models.Backend.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: models.Backend.access_level:type_name -> models.AccessLevel
	2, // 4: models.Backend.script_handler:type_name -> models.ScriptHandler
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_protos_backend_proto_init() }
func file_protos_backend_proto_init() {
	if File_protos_backend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_backend_proto_rawDesc), len(file_protos_backend_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_backend_proto_goTypes,
		DependencyIndexes: file_protos_backend_proto_depIdxs,
		EnumInfos:         file_protos_backend_proto_enumTypes,
		MessageInfos:      file_protos_backend_proto_msgTypes,
	}.Build()
	File_protos_backend_proto = out.File
	file_protos_backend_proto_goTypes = nil
	file_protos_backend_proto_depIdxs = nil
}
