// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: protos/configuration.proto

package models

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Ref: config -> Configuration (singleton)
type Configuration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	SiteFqdn      string                 `protobuf:"bytes,2,opt,name=site_fqdn,json=siteFqdn,proto3" json:"site_fqdn,omitempty"`
	AdminFqdn     string                 `protobuf:"bytes,3,opt,name=admin_fqdn,json=adminFqdn,proto3" json:"admin_fqdn,omitempty"`
	IsInTestMode  bool                   `protobuf:"varint,4,opt,name=is_in_test_mode,json=isInTestMode,proto3" json:"is_in_test_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_protos_configuration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_protos_configuration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration.ProtoReflect.Descriptor instead.
func (*Configuration) Descriptor() ([]byte, []int) {
	return file_protos_configuration_proto_rawDescGZIP(), []int{0}
}

func (x *Configuration) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Configuration) GetSiteFqdn() string {
	if x != nil {
		return x.SiteFqdn
	}
	return ""
}

func (x *Configuration) GetAdminFqdn() string {
	if x != nil {
		return x.AdminFqdn
	}
	return ""
}

func (x *Configuration) GetIsInTestMode() bool {
	if x != nil {
		return x.IsInTestMode
	}
	return false
}

var File_protos_configuration_proto protoreflect.FileDescriptor

const file_protos_configuration_proto_rawDesc = "" +
	"\n" +
	"\x1aprotos/configuration.proto\x12\x06models\"\x8e\x01\n" +
	"\rConfiguration\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1b\n" +
	"\tsite_fqdn\x18\x02 \x01(\tR\bsiteFqdn\x12\x1d\n" +
	"\n" +
	"admin_fqdn\x18\x03 \x01(\tR\tadminFqdn\x12%\n" +
	"\x0fis_in_test_mode\x18\x04 \x01(\bR\fisInTestModeJ\x04\b\x05\x10\x06B\x11Z\x0f./server/modelsb\x06proto3"

var (
	file_protos_configuration_proto_rawDescOnce sync.Once
	file_protos_configuration_proto_rawDescData []byte
)

func file_protos_configuration_proto_rawDescGZIP() []byte {
	file_protos_configuration_proto_rawDescOnce.Do(func() {
		file_protos_configuration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_configuration_proto_rawDesc), len(file_protos_configuration_proto_rawDesc)))
	})
	return file_protos_configuration_proto_rawDescData
}

var file_protos_configuration_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_configuration_proto_goTypes = []any{
	(*Configuration)(nil), // 0: models.Configuration
}
var file_protos_configuration_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_configuration_proto_init() }
func file_protos_configuration_proto_init() {
	if File_protos_configuration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_configuration_proto_rawDesc), len(file_protos_configuration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_configuration_proto_goTypes,
		DependencyIndexes: file_protos_configuration_proto_depIdxs,
		MessageInfos:      file_protos_configuration_proto_msgTypes,
	}.Build()
	File_protos_configuration_proto = out.File
	file_protos_configuration_proto_goTypes = nil
	file_protos_configuration_proto_depIdxs = nil
}
