// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: protos/credential.proto

package models

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebAuthnCredential struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	CredentialId []byte                 `protobuf:"bytes,1,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	PublicKeyDer []byte                 `protobuf:"bytes,2,opt,name=public_key_der,json=publicKeyDer,proto3" json:"public_key_der,omitempty"`
	Transports   []string               `protobuf:"bytes,3,rep,name=transports,proto3" json:"transports,omitempty"`
	// Authenticator
	Aaguid       []byte `protobuf:"bytes,4,opt,name=aaguid,proto3" json:"aaguid,omitempty"`
	SignCount    uint32 `protobuf:"varint,5,opt,name=sign_count,json=signCount,proto3" json:"sign_count,omitempty"`
	CloneWarning bool   `protobuf:"varint,6,opt,name=clone_warning,json=cloneWarning,proto3" json:"clone_warning,omitempty"`
	Attachment   string `protobuf:"bytes,7,opt,name=attachment,proto3" json:"attachment,omitempty"`
	// CredentialFlags
	FlagUserPresent    bool `protobuf:"varint,8,opt,name=flag_user_present,json=flagUserPresent,proto3" json:"flag_user_present,omitempty"`
	FlagUserVerified   bool `protobuf:"varint,9,opt,name=flag_user_verified,json=flagUserVerified,proto3" json:"flag_user_verified,omitempty"`
	FlagBackupEligible bool `protobuf:"varint,10,opt,name=flag_backup_eligible,json=flagBackupEligible,proto3" json:"flag_backup_eligible,omitempty"`
	FlagBackupState    bool `protobuf:"varint,11,opt,name=flag_backup_state,json=flagBackupState,proto3" json:"flag_backup_state,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WebAuthnCredential) Reset() {
	*x = WebAuthnCredential{}
	mi := &file_protos_credential_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebAuthnCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebAuthnCredential) ProtoMessage() {}

func (x *WebAuthnCredential) ProtoReflect() protoreflect.Message {
	mi := &file_protos_credential_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebAuthnCredential.ProtoReflect.Descriptor instead.
func (*WebAuthnCredential) Descriptor() ([]byte, []int) {
	return file_protos_credential_proto_rawDescGZIP(), []int{0}
}

func (x *WebAuthnCredential) GetCredentialId() []byte {
	if x != nil {
		return x.CredentialId
	}
	return nil
}

func (x *WebAuthnCredential) GetPublicKeyDer() []byte {
	if x != nil {
		return x.PublicKeyDer
	}
	return nil
}

func (x *WebAuthnCredential) GetTransports() []string {
	if x != nil {
		return x.Transports
	}
	return nil
}

func (x *WebAuthnCredential) GetAaguid() []byte {
	if x != nil {
		return x.Aaguid
	}
	return nil
}

func (x *WebAuthnCredential) GetSignCount() uint32 {
	if x != nil {
		return x.SignCount
	}
	return 0
}

func (x *WebAuthnCredential) GetCloneWarning() bool {
	if x != nil {
		return x.CloneWarning
	}
	return false
}

func (x *WebAuthnCredential) GetAttachment() string {
	if x != nil {
		return x.Attachment
	}
	return ""
}

func (x *WebAuthnCredential) GetFlagUserPresent() bool {
	if x != nil {
		return x.FlagUserPresent
	}
	return false
}

func (x *WebAuthnCredential) GetFlagUserVerified() bool {
	if x != nil {
		return x.FlagUserVerified
	}
	return false
}

func (x *WebAuthnCredential) GetFlagBackupEligible() bool {
	if x != nil {
		return x.FlagBackupEligible
	}
	return false
}

func (x *WebAuthnCredential) GetFlagBackupState() bool {
	if x != nil {
		return x.FlagBackupState
	}
	return false
}

// Ref: "cred:$id" -> Credential
// Ref: "user:$user_id:cred:$id" -> []
type Credential struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name               string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBySessionId string                 `protobuf:"bytes,6,opt,name=created_by_session_id,json=createdBySessionId,proto3" json:"created_by_session_id,omitempty"`
	LastUsedAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	UsedBySessionIds   []string               `protobuf:"bytes,8,rep,name=used_by_session_ids,json=usedBySessionIds,proto3" json:"used_by_session_ids,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*Credential_WebauthnCredential
	Type          isCredential_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credential) Reset() {
	*x = Credential{}
	mi := &file_protos_credential_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credential) ProtoMessage() {}

func (x *Credential) ProtoReflect() protoreflect.Message {
	mi := &file_protos_credential_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credential.ProtoReflect.Descriptor instead.
func (*Credential) Descriptor() ([]byte, []int) {
	return file_protos_credential_proto_rawDescGZIP(), []int{1}
}

func (x *Credential) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Credential) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Credential) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Credential) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Credential) GetCreatedBySessionId() string {
	if x != nil {
		return x.CreatedBySessionId
	}
	return ""
}

func (x *Credential) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

func (x *Credential) GetUsedBySessionIds() []string {
	if x != nil {
		return x.UsedBySessionIds
	}
	return nil
}

func (x *Credential) GetType() isCredential_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Credential) GetWebauthnCredential() *WebAuthnCredential {
	if x != nil {
		if x, ok := x.Type.(*Credential_WebauthnCredential); ok {
			return x.WebauthnCredential
		}
	}
	return nil
}

type isCredential_Type interface {
	isCredential_Type()
}

type Credential_WebauthnCredential struct {
	WebauthnCredential *WebAuthnCredential `protobuf:"bytes,5,opt,name=webauthn_credential,json=webauthnCredential,proto3,oneof"`
}

func (*Credential_WebauthnCredential) isCredential_Type() {}

var File_protos_credential_proto protoreflect.FileDescriptor

const file_protos_credential_proto_rawDesc = "" +
	"\n" +
	"\x17protos/credential.proto\x12\x06models\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb3\x03\n" +
	"\x12WebAuthnCredential\x12#\n" +
	"\rcredential_id\x18\x01 \x01(\fR\fcredentialId\x12$\n" +
	"\x0epublic_key_der\x18\x02 \x01(\fR\fpublicKeyDer\x12\x1e\n" +
	"\n" +
	"transports\x18\x03 \x03(\tR\n" +
	"transports\x12\x16\n" +
	"\x06aaguid\x18\x04 \x01(\fR\x06aaguid\x12\x1d\n" +
	"\n" +
	"sign_count\x18\x05 \x01(\rR\tsignCount\x12#\n" +
	"\rclone_warning\x18\x06 \x01(\bR\fcloneWarning\x12\x1e\n" +
	"\n" +
	"attachment\x18\a \x01(\tR\n" +
	"attachment\x12*\n" +
	"\x11flag_user_present\x18\b \x01(\bR\x0fflagUserPresent\x12,\n" +
	"\x12flag_user_verified\x18\t \x01(\bR\x10flagUserVerified\x120\n" +
	"\x14flag_backup_eligible\x18\n" +
	" \x01(\bR\x12flagBackupEligible\x12*\n" +
	"\x11flag_backup_state\x18\v \x01(\bR\x0fflagBackupState\"\xfb\x02\n" +
	"\n" +
	"Credential\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x121\n" +
	"\x15created_by_session_id\x18\x06 \x01(\tR\x12createdBySessionId\x12<\n" +
	"\flast_used_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\x12-\n" +
	"\x13used_by_session_ids\x18\b \x03(\tR\x10usedBySessionIds\x12M\n" +
	"\x13webauthn_credential\x18\x05 \x01(\v2\x1a.models.WebAuthnCredentialH\x00R\x12webauthnCredentialB\x06\n" +
	"\x04typeB\x11Z\x0f./server/modelsb\x06proto3"

var (
	file_protos_credential_proto_rawDescOnce sync.Once
	file_protos_credential_proto_rawDescData []byte
)

func file_protos_credential_proto_rawDescGZIP() []byte {
	file_protos_credential_proto_rawDescOnce.Do(func() {
		file_protos_credential_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_credential_proto_rawDesc), len(file_protos_credential_proto_rawDesc)))
	})
	return file_protos_credential_proto_rawDescData
}

var file_protos_credential_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_credential_proto_goTypes = []any{
	(*WebAuthnCredential)(nil),    // 0: models.WebAuthnCredential
	(*Credential)(nil),            // 1: models.Credential
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_protos_credential_proto_depIdxs = []int32{
	2, // 0: models.Credential.created_at:type_name -> google.protobuf.Timestamp
	2, // 1: models.Credential.last_used_at:type_name -> google.protobuf.Timestamp
	0, // 2: models.Credential.webauthn_credential:type_name -> models.WebAuthnCredential
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_credential_proto_init() }
func file_protos_credential_proto_init() {
	if File_protos_credential_proto != nil {
		return
	}
	file_protos_credential_proto_msgTypes[1].OneofWrappers = []any{
		(*Credential_WebauthnCredential)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_credential_proto_rawDesc), len(file_protos_credential_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_credential_proto_goTypes,
		DependencyIndexes: file_protos_credential_proto_depIdxs,
		MessageInfos:      file_protos_credential_proto_msgTypes,
	}.Build()
	File_protos_credential_proto = out.File
	file_protos_credential_proto_goTypes = nil
	file_protos_credential_proto_depIdxs = nil
}
