// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: protos/mqtt-client.proto

package models

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Ref: mqtt-client:$id -> MqttClient
type MqttClient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProfileId     string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Values        map[string]string      `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MqttClient) Reset() {
	*x = MqttClient{}
	mi := &file_protos_mqtt_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MqttClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MqttClient) ProtoMessage() {}

func (x *MqttClient) ProtoReflect() protoreflect.Message {
	mi := &file_protos_mqtt_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MqttClient.ProtoReflect.Descriptor instead.
func (*MqttClient) Descriptor() ([]byte, []int) {
	return file_protos_mqtt_client_proto_rawDescGZIP(), []int{0}
}

func (x *MqttClient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MqttClient) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *MqttClient) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *MqttClient) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_protos_mqtt_client_proto protoreflect.FileDescriptor

const file_protos_mqtt_client_proto_rawDesc = "" +
	"\n" +
	"\x18protos/mqtt-client.proto\x12\x06models\"\xca\x01\n" +
	"\n" +
	"MqttClient\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x126\n" +
	"\x06values\x18\x04 \x03(\v2\x1e.models.MqttClient.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x11Z\x0f./server/modelsb\x06proto3"

var (
	file_protos_mqtt_client_proto_rawDescOnce sync.Once
	file_protos_mqtt_client_proto_rawDescData []byte
)

func file_protos_mqtt_client_proto_rawDescGZIP() []byte {
	file_protos_mqtt_client_proto_rawDescOnce.Do(func() {
		file_protos_mqtt_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_mqtt_client_proto_rawDesc), len(file_protos_mqtt_client_proto_rawDesc)))
	})
	return file_protos_mqtt_client_proto_rawDescData
}

var file_protos_mqtt_client_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_mqtt_client_proto_goTypes = []any{
	(*MqttClient)(nil), // 0: models.MqttClient
	nil,                // 1: models.MqttClient.ValuesEntry
}
var file_protos_mqtt_client_proto_depIdxs = []int32{
	1, // 0: models.MqttClient.values:type_name -> models.MqttClient.ValuesEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_mqtt_client_proto_init() }
func file_protos_mqtt_client_proto_init() {
	if File_protos_mqtt_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_mqtt_client_proto_rawDesc), len(file_protos_mqtt_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_mqtt_client_proto_goTypes,
		DependencyIndexes: file_protos_mqtt_client_proto_depIdxs,
		MessageInfos:      file_protos_mqtt_client_proto_msgTypes,
	}.Build()
	File_protos_mqtt_client_proto = out.File
	file_protos_mqtt_client_proto_goTypes = nil
	file_protos_mqtt_client_proto_depIdxs = nil
}
